version: '3.8'
services:
  sync-love-db:
    container_name: sync-love-db
    image: postgres
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB_HOST=${DB_HOST}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  data: {}
